version: "3.9"

services:
  frontend:
    build: ./frontend
    depends_on:
      - backend
    ports:
      - 3000:3000
    container_name: Frontend
  backend:
    depends_on:
      - mongodb
    build: ./backend
    ports:
      - 8000:8000
    container_name: Backend

  # Replica Set (required for Prisma Client)
  mongodb:
    container_name: MongoDB
    build: ./database
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: prisma
      MONGO_REPLICA_HOST: localhost
      MONGO_REPLICA_PORT: 27017
    ports:
      - '27018:27017'
