version: "3.9"

services:
  frontend:
    build: ./frontend
    depends_on:
      - backend
    ports:
      - 3000:3000
    container_name: Frontend
  backend:
    depends_on:
      - mongodb_migrate
    build: ./backend
    ports:
      - 8000:8000
    container_name: Backend

  mongodb_migrate:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: prisma
    ports:
      - '27017:27017'

  # Replica Set (required for Prisma Client)
  mongo:
    build: ./mongodb_replica
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: prisma
      MONGO_REPLICA_HOST: localhost
      MONGO_REPLICA_PORT: 27018
    ports:
      - '27018:27018'
